### ISSUE TITLE
KeyError: Strength

### ISSUE THREAD

**Issue by jbeard** [adammartin/pathfinder_editor#1]
Both in the manually built version I got here on github and the new version you just uploaded sometime  around 5:30pm EST on Saturday Oct 13, I receive the following error message when loading a save file on Mac OS X:

/Users/jbeard/Dropbox/GAMES/KINGMAKER/MODS/DOWNLOADED/Mac\ Editor\ \(Standalone\)-9-0-9-beta-1539466445/pathfinder_editor_mac/pathfinder_editor ; exit;
objc[36683]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffaaecfc90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11489ecd8). One of the two will be used. Which one is undefined.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/jbeard/Dropbox/GAMES/KINGMAKER/MODS/DOWNLOADED/Mac Editor (Standalone)-9-0-9-beta-1539466445/pathfinder_editor_mac/tkinter/__init__.py", line 1699, in __call__
  File "/Users/jbeard/Dropbox/GAMES/KINGMAKER/MODS/DOWNLOADED/Mac Editor (Standalone)-9-0-9-beta-1539466445/pathfinder_editor_mac/widgets/pathfinder_window.py", line 63, in _file_open
  File "/Users/jbeard/Dropbox/GAMES/KINGMAKER/MODS/DOWNLOADED/Mac Editor (Standalone)-9-0-9-beta-1539466445/pathfinder_editor_mac/widgets/tabs.py", line 19, in load_info
  File "/Users/jbeard/Dropbox/GAMES/KINGMAKER/MODS/DOWNLOADED/Mac Editor (Standalone)-9-0-9-beta-1539466445/pathfinder_editor_mac/widgets/tabs.py", line 59, in load_info
  File "/Users/jbeard/Dropbox/GAMES/KINGMAKER/MODS/DOWNLOADED/Mac Editor (Standalone)-9-0-9-beta-1539466445/pathfinder_editor_mac/player_info.py", line 19, in strength
  File "/Users/jbeard/Dropbox/GAMES/KINGMAKER/MODS/DOWNLOADED/Mac Editor (Standalone)-9-0-9-beta-1539466445/pathfinder_editor_mac/player_info.py", line 74, in _load_attribute_value
KeyError: 'Strength'

The "Money" and "Experience" fields have the appropriate values in them for the save game, and the character name is correct.... but all other fields are blank and attempting to edit and save produces no result.

Looking at the raw source after decompressing the ZKS file, the values appear correct.

I'm noodling around trying to figure out the source issue. I could provide my save file if that would be helpful.

**Comment by adammartin** [comment]
I'm assuming this is fixed now.

I should have been better at paying attention to issues @jbeard let me know if you are up and running.  I'm super sorry and apologize for not paying better attention!
